version: 2
jobs:
  cloud-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, this is dev"
  cloud-production:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "hello engineers"
          command: "echo this is productoin"
workflows:
  version: 2
  build-dev-workflows:
    jobs:
      - cloud-dev:
          filters:
            branches:
              only: test
    build-production-workflows:
      jobs:
      - cloud-production:
          filters:
            branches:
              only: master
