# Javascript Node CircleCI 2.0 configuration file
version: 2
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    docker:
      - image: circleci/node:13.14.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the application
          command: sudo apt intall make 
  deploy-test:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          #Get all pre-requisites
          name: install package 
          command: make
            
  deploy-production:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run:
          #Get all pre-requisites
          name: install package 
          command: make
           
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy-test:
          context: AWS
          filters:
            branches:
              only:
                - test
  build-production-workflows:
    jobs:
     - deploy-production:
        filters:
          branches:
            only: master
