version: 2.1

jobs:
  cloud-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - when:
          condition:
            equal: ['true', 'false']
          steps:
              - checkout
              - run:
                  name: "Say hello world"
                  command: "echo Hello, this is dev"
  cloud-production:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "hello engineers"
          command: "echo this is productoin"
  Deployment:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Running deployment on ECS"
workflows:
  version: 2
  build-dev-workflows:
    jobs:
      - cloud-dev:
          context: dev
          filters:
            branches:
              only: test
      - Deployment:
          filters:
            branches:
              only: test
  build-production-workflows:
    jobs:
    - cloud-production:
        filters:
          branches:
            only: master


