version: 2
jobs:
  app-deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          #Get all pre-requisites
          name: install package
          command: | 
            apk add --no-cache \
            py-pip=9.0.0-r1 
            pip install --upgrade pip \
            awscli==1.14.37
            apk update && apk upgrade && apk add --update alpine-sdk && \
            apk add --no-cache bash git openssh make cmake     
            make sync       
workflows:
  version: 2
  build-test-workflows:
    jobs:
      - app-deploy:
          context: AWS
          filters:
            branches:
              only:
                - test
  build-production-workflows:
    jobs:
      - app-deploy:
          context: AWS
          filters:
            branches:
              only:
               - master

