# Javascript Node CircleCI 2.0 configuration fi
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.14.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the application
          command: echo "build app"
  deploy-test:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          #Get all pre-requisites
          name: install package
          command: | 
            apk update  && apk add --update alpine-sdk && \
            apk add --no-cache bash git openssh make cmake 
            sudo apt-get -y -qq update
            sudo apt-get install -y awscli
            sudo apt-get install -y python-pip python-dev build-essential
            aws s3 sync . s3://zohaibcircleci	
  deploy-production:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - run:
          #Get all pre-requisites
          name: install all packge
          command: make package         
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy-test:
          context: AWS
          filters:
            branches:
              only:
                - test
  build-production-workflows:
    jobs:
     - deploy-production:
        filters:
          branches:
            only: master
