version: 2.1
jobs:
  cloud-dev:
    docker:
      - image: cimg/base:stable
  
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, this is dev"
jobs:
  cloud-stagging:
    docker:
      - image: cimg/base:stable
   
    steps:
      - checkout
      - run:
          name: "hello engineers"
          command: "echo this is stagging"
jobs:
  clouds-production:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "hello engineers"
          command: "echo this is productoin"
workflows:
  build-test-workflows:
    jobs:
      - cloud-dev
      - cloud-stagging:
          requires:
            - cloud-dev
          filters:
            branches:
              only:
                - test
  build-production-workflows:
    jobs:
 - cloud-production:
          requires:
            - cloud-dev
            - cloud-stagging
          filters:
            branches:
              only:
                - master